import Navbar from '@/components/navbar/page'
import '../globals.css'
import type { Metadata } from 'next'
import { Oswald } from 'next/font/google'
import FeaturedProducts from '@/components/shop/featured/page'
import OnSale from '@/components/shop/onsale/page'
import ProductReviews from '@/components/shop/reviews/page'

const oswald = Oswald({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${oswald.className} scroll-smooth`}>
        <Navbar />
        {children}
        <FeaturedProducts />
        <OnSale />
        <ProductReviews />

      </body>
    </html>
  )
}
